In [27]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, accuracy_score, f1_score
import pickle

Random Forest Classification Model

In [28]:
train_final_df = pd.read_csv('train_df_final.csv')
test_final_df = pd.read_csv('test_df_final.csv')

In [29]:
X_train = train_final_df.drop(columns=["Image name", "New Retinopathy Grade","Optic Disc Area","Edge_Density","Std_Deviation","Exudate Density"])
y_train = train_final_df["New Retinopathy Grade"]
X_test = test_final_df.drop(columns=["Image name", "New Retinopathy Grade","Optic Disc Area","Edge_Density","Std_Deviation","Exudate Density"])
y_test = test_final_df["New Retinopathy Grade"]

In [30]:
X_test.head()

,MA Ratio,Vessel Length,Vessel Tortuosity,Mean_Intensity
0,0.016201,16616,1.553983,27.543258
1,0.022860,26817,1.542775,41.831461
2,0.009889,30009,1.558268,52.665440
3,0.040811,71288,1.418744,65.251439
4,0.005705,19307,1.556777,42.553625


In [31]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
def model_evaluation(y_test, y_pred, model_name):
    # Classification Report
    print("Classification report for", model_name, "\n")
    print(classification_report(y_test, y_pred))

    # Accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)

In [33]:
model_name="RANDOM FOREST"

In [34]:
rf=RandomForestClassifier(n_estimators=128, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=128, random_state=42)

In [35]:
y_pred_rf=rf.predict(X_test)

In [36]:
f1_score_rf=f1_score(y_test, y_pred_rf, average="weighted")
print(f1_score_rf)

0.7259782288908503


In [37]:
model_evaluation(y_test,y_pred_rf,model_name)

Classification report for RANDOM FOREST 

              precision    recall  f1-score   support

           0       0.59      0.56      0.58        34
           1       0.79      0.81      0.80        69

    accuracy                           0.73       103
   macro avg       0.69      0.69      0.69       103
weighted avg       0.72      0.73      0.73       103

Accuracy: 0.7281553398058253


In [38]:
## Create a pickle file using serialization ##

pickle_out = open("model.pkl", "wb")
pickle_scaler = open("scaler.pkl", "wb")
pickle.dump(scaler, pickle_scaler)
pickle.dump( rf, pickle_out)
pickle_out.close()
pickle_scaler.close()

In [39]:
scaler.transform([[0, 6482, 2.18772351769377, 63.59237453332012]])[0]

/Users/abhinavkumarna/Documents/Temp/Dibetic-RD/temp/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([ 0.        , -0.00422991,  1.91703619,  0.54089621])

In [40]:
rf.predict(scaler.transform([[0, 12151, 2.1139642303936297, 52.00636409201224]]))

/Users/abhinavkumarna/Documents/Temp/Dibetic-RD/temp/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([1])

In [41]:
rf.predict(scaler.transform([[0.016201,16616,1.553983,2.543258]]))

/Users/abhinavkumarna/Documents/Temp/Dibetic-RD/temp/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([0])